# Generated by Django 5.2.1 on 2025-10-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_seed_initial_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='body_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('coupe', 'Coupe'), ('hatchback', 'Hatchback'), ('truck', 'Truck'), ('van', 'Van'), ('other', 'Other')], default='sedan', max_length=30),
        ),
        migrations.AddField(
            model_name='carvariant',
            name='transmission',
            field=models.CharField(choices=[('automatic', 'Automatic'), ('manual', 'Manual'), ('cvt', 'CVT'), ('dual-clutch', 'Dual Clutch'), ('other', 'Other')], default='automatic', max_length=20),
        ),
    ]
