# Generated by Django 5.2.1 on 2025-10-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_populate_vehicle_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariant',
            name='listing_type',
            field=models.CharField(choices=[('registered', 'Registered'), ('foreign-used', 'Foreign Used')], default='registered', max_length=20),
        ),
    ]
