# Generated by Django 5.2.1 on 2025-10-11 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_populate_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBrandMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('value', models.CharField(max_length=40)),
                ('label', models.CharField(max_length=160)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage brand metric',
                'verbose_name_plural': 'Homepage brand metrics',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=120)),
                ('icon', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage category',
                'verbose_name_plural': 'Homepage categories',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageContactCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('link_label', models.CharField(blank=True, max_length=120)),
                ('link_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage contact card',
                'verbose_name_plural': 'Homepage contact cards',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageFinancingHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage financing highlight',
                'verbose_name_plural': 'Homepage financing highlights',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageFinancingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage financing step',
                'verbose_name_plural': 'Homepage financing steps',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('badge_label', models.CharField(blank=True, max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.TextField(blank=True)),
                ('primary_cta_label', models.CharField(blank=True, max_length=120)),
                ('primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage hero',
                'verbose_name_plural': 'Homepage heroes',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageSectionCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('heading', models.CharField(blank=True, max_length=180)),
                ('subheading', models.CharField(blank=True, max_length=255)),
                ('supporting_text', models.CharField(blank=True, max_length=255)),
                ('cta_label', models.CharField(blank=True, max_length=120)),
                ('cta_url', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage section copy',
                'verbose_name_plural': 'Homepage section copy',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='HomepageValueProposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Homepage value proposition',
                'verbose_name_plural': 'Homepage value propositions',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='NavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navigation link',
                'verbose_name_plural': 'Navigation links',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HomepageFeaturedVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=180)),
                ('price', models.CharField(blank=True, max_length=120)),
                ('payment_plan', models.CharField(blank=True, max_length=160)),
                ('image_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('badge', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='featured_entries', to='marketing.carvariant')),
            ],
            options={
                'verbose_name': 'Homepage featured vehicle',
                'verbose_name_plural': 'Homepage featured vehicles',
                'ordering': ('order', 'id'),
            },
        ),
    ]
