# Generated by Django 5.2.1 on 2025-10-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_homepagebrandmetric_homepagecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('all', 'All Cars'), ('registered', 'Registered Cars'), ('foreign-used', 'Foreign Used Cars')], max_length=40, unique=True)),
                ('listing_type', models.CharField(blank=True, choices=[('registered', 'Registered'), ('foreign-used', 'Foreign Used')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=180)),
                ('intro_text', models.TextField(blank=True)),
                ('page_kicker', models.CharField(blank=True, max_length=80)),
                ('summary_badge_label', models.CharField(blank=True, max_length=120)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Inventory page configuration',
                'verbose_name_plural': 'Inventory page configurations',
                'ordering': ('slug',),
            },
        ),
    ]
