# Generated by Django 5.2.1 on 2025-10-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_inventorypageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancingBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financing benefit',
                'verbose_name_plural': 'Financing benefits',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='FinancingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(choices=[('financing', 'Financing Page')], max_length=40, unique=True)),
                ('hero_title', models.CharField(blank=True, max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_primary_cta_label', models.CharField(blank=True, max_length=120)),
                ('hero_primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('hero_secondary_cta_label', models.CharField(blank=True, max_length=120)),
                ('hero_secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('hero_background_image_url', models.URLField(blank=True)),
                ('hero_callout_title', models.CharField(blank=True, max_length=160)),
                ('hero_callout_text', models.CharField(blank=True, max_length=255)),
                ('steps_heading', models.CharField(blank=True, max_length=200)),
                ('steps_subheading', models.CharField(blank=True, max_length=255)),
                ('benefits_heading', models.CharField(blank=True, max_length=200)),
                ('benefits_subheading', models.CharField(blank=True, max_length=255)),
                ('eligibility_heading', models.CharField(blank=True, max_length=180)),
                ('eligibility_description', models.TextField(blank=True)),
                ('eligibility_cta_label', models.CharField(blank=True, max_length=160)),
                ('eligibility_cta_url', models.CharField(blank=True, max_length=255)),
                ('testimonial_image_url', models.URLField(blank=True)),
                ('testimonial_card_title', models.CharField(blank=True, max_length=160)),
                ('testimonial_card_text', models.CharField(blank=True, max_length=255)),
                ('corporate_heading', models.CharField(blank=True, max_length=200)),
                ('corporate_subheading', models.CharField(blank=True, max_length=255)),
                ('corporate_primary_cta_label', models.CharField(blank=True, max_length=160)),
                ('corporate_primary_cta_url', models.CharField(blank=True, max_length=255)),
                ('corporate_secondary_cta_label', models.CharField(blank=True, max_length=160)),
                ('corporate_secondary_cta_url', models.CharField(blank=True, max_length=255)),
                ('corporate_availability_heading', models.CharField(blank=True, max_length=160)),
                ('corporate_availability_description', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financing page configuration',
                'verbose_name_plural': 'Financing page configurations',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='FinancingSnapshotItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Financing snapshot item',
                'verbose_name_plural': 'Financing snapshot items',
                'ordering': ('order', 'id'),
            },
        ),
    ]
