# Generated by Django 5.2.1 on 2025-10-11 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0009_financingbenefit_financingpageconfig_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarVariantDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('subheadline', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mileage_km', models.PositiveIntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('finance_intro', models.CharField(blank=True, max_length=255)),
                ('loan_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate percentage', max_digits=5, null=True)),
                ('loan_deposit_percent', models.DecimalField(blank=True, decimal_places=2, help_text='Deposit percentage e.g. 30', max_digits=5, null=True)),
                ('loan_period_months', models.PositiveIntegerField(blank=True, null=True)),
                ('applicant_types', models.CharField(blank=True, help_text='Comma separated list of applicant types', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='marketing.carvariant')),
            ],
            options={
                'verbose_name': 'Car variant detail',
                'verbose_name_plural': 'Car variant details',
            },
        ),
        migrations.CreateModel(
            name='CarVariantFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='marketing.carvariant')),
            ],
            options={
                'verbose_name': 'Car variant feature',
                'verbose_name_plural': 'Car variant features',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CarVariantImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('image_url', models.URLField()),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='marketing.carvariant')),
            ],
            options={
                'verbose_name': 'Car variant image',
                'verbose_name_plural': 'Car variant images',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CarVariantSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=160)),
                ('value', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='marketing.carvariant')),
            ],
            options={
                'verbose_name': 'Car variant specification',
                'verbose_name_plural': 'Car variant specifications',
                'ordering': ('order', 'id'),
            },
        ),
    ]
