# Generated by Django 5.0.14 on 2025-10-11 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_carvariantdetail_carvariantfeature_carvariantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='carvariantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='car_variants/'),
        ),
        migrations.AlterField(
            model_name='carvariantimage',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
